[package]
name = "idata"
version = "0.1.2"
authors = ["jlehahred <jleahred@gmail.com>"]
license = "GPL-3.0"
description = "Small tools to reduce mutability"
readme = "README.md"
repository = "https://github.com/jleahred/idata"
keywords = ["functional", "mutability"]

[dependencies]

